### PR TITLE
docs: update to new doc format

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

**Fixes:** #3

## Summary:

Updates repo to use latest version of component doc system format.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [x] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by blackfalcon** [comment]
I am going to suggest an alternative to this. I suggest using the [upgrade process](https://auro.alaskaair.com/getting-started/developers/generator/upgrade) and migrate over the demo files from this PR. 

Let me know if that makes sense or not.

**Comment by blackfalcon** [comment]
Relabeled to `work in progress`. Waiting for updated PR based on the new repo migration tool.

**Comment by jason-capsule42** [comment]
> I am going to suggest an alternative to this. I suggest using the [upgrade process](https://auro.alaskaair.com/getting-started/developers/generator/upgrade) and migrate over the demo files from this PR.
> 
> Let me know if that makes sense or not.

@blackfalcon Per discussion earlier today - this is the PR that was mistakenly relabeled due to misunderstanding on what work was done here. This work was done using the upgrade process and is ready for review.

**Review by blackfalcon — CHANGES_REQUESTED** [review]
The demo page looks great, but you are missing the support needed to run the markdown demo correctly. 

This PR does a full migration to a new generator build and pulls over the demo.md file you created. 

https://github.com/AlaskaAirlines/auro-datetime/pull/7

**Comment by jason-capsule42** [comment]
Closing this out and using PR #7 instead

**Pull request closed without merging**
